# Generated by Django 4.2.4 on 2023-09-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentBasedSongGenres",
            fields=[
                ("valence", models.FloatField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("acousticness", models.FloatField(blank=True, null=True)),
                ("artists", models.CharField(blank=True, null=True)),
                ("danceability", models.FloatField(blank=True, null=True)),
                ("duration_ms", models.FloatField(blank=True, null=True)),
                ("energy", models.FloatField(blank=True, null=True)),
                ("explicit", models.IntegerField(blank=True, null=True)),
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("instrumentalness", models.FloatField(blank=True, null=True)),
                ("key", models.IntegerField(blank=True, null=True)),
                ("liveness", models.FloatField(blank=True, null=True)),
                ("loudness", models.FloatField(blank=True, null=True)),
                ("mode", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, null=True)),
                ("popularity", models.IntegerField(blank=True, null=True)),
                ("release_date", models.CharField(blank=True, null=True)),
                ("speechiness", models.FloatField(blank=True, null=True)),
                ("tempo", models.FloatField(blank=True, null=True)),
            ],
            options={"db_table": "content_based_song_genres", "managed": False,},
        ),
        migrations.CreateModel(
            name="ContentBasedStyleGenres",
            fields=[
                ("mode", models.IntegerField(blank=True, null=True)),
                ("genres", models.CharField(primary_key=True, serialize=False)),
                ("acousticness", models.FloatField(blank=True, null=True)),
                ("danceability", models.FloatField(blank=True, null=True)),
                ("duration_ms", models.FloatField(blank=True, null=True)),
                ("energy", models.FloatField(blank=True, null=True)),
                ("instrumentalness", models.FloatField(blank=True, null=True)),
                ("liveness", models.FloatField(blank=True, null=True)),
                ("loudness", models.FloatField(blank=True, null=True)),
                ("speechiness", models.FloatField(blank=True, null=True)),
                ("tempo", models.FloatField(blank=True, null=True)),
                ("valence", models.FloatField(blank=True, null=True)),
                ("popularity", models.FloatField(blank=True, null=True)),
                ("key", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "content_based_style_genres",
                "db_table_comment": "音樂屬性",
                "managed": False,
            },
        ),
    ]
