# Generated by Django 4.2.5 on 2023-09-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserBasedDataset",
            fields=[
                (
                    "user_id",
                    models.CharField(blank=True, primary_key=True, serialize=False),
                ),
                ("song_id", models.CharField(blank=True, null=True)),
                ("listen_count", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, null=True)),
                ("release", models.CharField(blank=True, null=True)),
                ("artist_name", models.CharField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_based_dataset",
                "managed": False,
            },
        ),
    ]
